services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: wsd_taskboard
      POSTGRES_USER: wsd
      POSTGRES_PASSWORD: wsdpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wsd -d wsd_taskboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    # Важливо: синхронізуємо локальну папку backend з папкою в контейнері
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_KEY=base64:8cV/k0MyY0gR7k7mPD7coT42E/mc1FLLDpt1RslQX7c=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=wsd_taskboard
      - DB_USERNAME=wsd
      - DB_PASSWORD=wsdpass
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - REDIS_CLIENT=predis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build: ./frontend
    ports:
      - "8080:80"
    # Також додаємо volumes для фронтенду, щоб бачити зміни в JS/HTML без перезбірки
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
